### ISSUE TITLE
'System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\home\site\wwwroot\runtimes\unix\'.

### ISSUE THREAD

**Issue by VikramVasudevan** [Azure/Commercial-Marketplace-SaaS-Accelerator#95]
**Bug Description**
First of all, Thanks for the great application. Unfortunately I am unable to deploy successfully. The ARM template deployment step gives the following error.

.\Deploy.ps1  -WebAppNamePrefix "XXXXXXXX"    -TenantID "XXXXXX"    -ADApplicationID "XXXXX"    -ADApplicationSecret "XXXXX"    -SQLServerName "XXXXX"    -SQLAdminLogin "XXXXXX"    -SQLAdminLoginPassword "XXXXX"    -PublisherAdminUsers "XXXXXXX"    -BacpacUrl "someurl"    -ResourceGroupForDeployment "XXXXX"    -Location "East US"    -AzureSubscriptionID "XXXXX"    -PathToARMTemplate "\path\to\deploy.json" 

(actual values masked for security)

`Package deployment failed                                                                                                                                                                    AppGallery Deploy Failed: 'System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\home\site\wwwroot\runtimes\unix\'.                                                          at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)                                                                         at Microsoft.Web.Deployment.FileStreamEx.CreateInstance(String path, FileMode fileMode, FileAccess fileAccess, FileShare fileShare, Nullable 1 fileLength)                                      at Microsoft.Web.Deployment.FilePathProviderBase.Add(DeploymentObject source, Boolean whatIf)                                                                                                   at Microsoft.Web.Deployment.DeploymentObject.AddChild(DeploymentObject source, Int32 position, DeploymentSyncContext syncContext)                                                               at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAddChild(DeploymentObject destParent, DeploymentObject sourceObject, Int32 position)                                                    at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)                                                                   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)                                                                                  at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)                                                                           at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)                                                                                  at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)                                                                             at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)                                                                                  at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)                                                                at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable,    Nullable1 syncPassId, String syncSessionId)                                                                                                                                                       at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)                            at Microsoft.Web.Deployment.DeploymentObject.SyncTo(String provider, String path, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)                                         at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentWellKnownProvider provider, String path, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)                    at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.Deploy(String deploymentSite, String siteSlotId, Boolean doNotDelete)                                                                      at Microsoft.Web.Deployment.WebApi.DeploymentController.&amp;lt;DownloadAndDeployPackage&amp;gt;d__24.MoveNext()'                                                                            Package deployment failed                               
`

**To Reproduce**
Follow step by step the instructions provided.  In the end, the deploy step always fails with the error above. I have tried removing the entire resource group and rerunning the whole script. 
The script fails at the point where it says "Deploying the ARM template to set up resources"

**Expected behavior**
All resources should be deployed successfully without any errors.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser - Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

**Comment by VikramVasudevan** [comment]
Update : When I deployed through the Visual Studio deploy functionality, I dont get this error and I was able to access the applications (both portal and admin). So the Deploy.ps1 must have some issues?

**Comment by lostmsu** [comment]
@VikramVasudevan how did you deploy databases through VS? Did you not use the ARM template?

**Comment by VikramVasudevan** [comment]
> I've got the same issue.
> 
> @VikramVasudevan how did you deploy databases through VS? Did you not use the ARM template?

@lostmsu - Yes I did use the ARM template (well I had to run Deploy.ps1 which in turn kicks off the ARM). However it kept failing in the app service deployment step as I have stated above. the databases got deployed successfully though when I ran Deploy.ps1.

**Comment by dev-kiranbanda** [comment]
Hi all,

Sorry for the delay in getting to this.

I had faced this issue myself when I created the ARM template and the powershell script.

Please note the *Note* in the installation instructions:

> Note: Make sure that you are using the latest Powershell to avoid issues in Compress-Archive in 5.1 that got resolved in latest version.

You need to have the right Powershell installed and make sure that you are opening the Powershell command window that corresponds to the latest version. This is a step that is commonly missed and this is the cause for the behavior that you have.

The issue is due to the difference in the path separator between Windows and Unix / Linux.

Please give it a try and keep me posted.

Regards,
Kiran Banda

**Comment by yurych** [comment]
I'm still seeing this error when running `New-AzureServiceRollout` command:
```
ARM-MSDeploy Deploy Failed: 'System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\home\site\wwwroot\runtimes\unix\'
```
`AzureServiceDeployClient` is still starting powershell version 5.1.22000.653

**Comment by yurych** [comment]
It turns out `New-AzureServiceRollout` is not an issue. Ev2 CLI and Ev2 SDK have the same problem in powershell 5.x because  `Compress-Archive` in poweshell 5.x works differently than in poweshell 7.x.  If I create a zip archive in powershell 7.x and then use `New-AzureServiceRollout` in powershell 5.x or simply use Ev2 SDK console app to start a rollout, the rollout succeeds.
